export const SEARCH_SOLICITUDES_START = 'SEARCH_SOLICITUDES_START';
export const SEARCH_SOLICITUDES_ERROR = 'SEARCH_SOLICITUDES_ERROR';
export const SEARCH_SOLICITUDES_COMPLETE = 'SEARCH_SOLICITUDES';